modLoader="javafml"
loaderVersion="[39,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="merchantmarkers"
version="${file.jarVersion}"
displayName="Merchant Markers"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-curse-update-checker.herokuapp.com/549275"
logoFile="icon.png"
authors="Grend"
description='''Adds floating markers above villagers to indicate their professions.'''

[[dependencies.merchantmarkers]]
	modId="forge"
	mandatory=true
	versionRange="[39,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.merchantmarkers]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.1,1.19)"
	ordering="NONE"
	side="BOTH"

[[dependencies.merchantmarkers]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.39,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.merchantmarkers]]
	modId="xaerominimap"
	mandatory=false
	versionRange="[21.22.3,)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.merchantmarkers]]
	modId="ftbchunks"
	mandatory=false
	versionRange="[1801.3.3,)"
	ordering="BEFORE"
	side="BOTH"
